### ISSUE TITLE
PvPInfo: Not able to queue due to disabled queue button

### ISSUE THREAD

**Issue by Thekinghim** [PvPAssistant/PvPAssistant#100]
#23 
![Skärmbild (277)](https://github.com/PvPAssistant/PvPAssistant/assets/151988881/cf9216e9-1768-44ee-8094-da79af2441e4)

**Comment by derfloh205** [comment]
We had this issue at one point
The solution at that time was that the addon should not have added PvP_UI from blizzard as deps as the preloading of the blizzard addon seemed to have broken something with the buttons

Might be a different issue here though but has definitely something to do with the blizz addon

**Comment by derfloh205** [comment]
Reason for this seems to be the manual loading of `Blizzard_PVPUI` in ArenaQuickJoin.lua

I temporarly disabled it on main until this is fixed
