### ISSUE TITLE
LFG: Tooltip LFG Groupleader

### ISSUE THREAD

**Issue by Thekinghim** [PvPAssistant/PvPAssistant#103]
No need for a description here the images says it all
![LFGHoverTooltip](https://github.com/PvPAssistant/PvPAssistant/assets/151988881/62711f5b-3d2d-4f26-9d87-ccbe34423559)

**Comment by derfloh205** [comment]
The "Last Updated" field tells us very clear that this seems to be data that arena master puts into the addon via updates

I can check though what data we can fetch via the lfg api ingame

**Comment by Thekinghim** [comment]
Yea u know I'm just thinking if there is a way to make it all automatic?
