### ISSUE TITLE
What is this error can someone please explain

### ISSUE THREAD

**Issue by Thekinghim** [PvPAssistant/PvPAssistant#106]
`Message: ...erface/AddOns/Blizzard_InspectUI/InspectPVPFrame.lua:71: Usage: local factionGroupTag, localized = UnitFactionGroup(unitName [, checkDisplayRace])
Time: Fri Apr  5 22:47:11 2024
Count: 11
Stack: ...erface/AddOns/Blizzard_InspectUI/InspectPVPFrame.lua:71: Usage: local factionGroupTag, localized = UnitFactionGroup(unitName [, checkDisplayRace])
[string "=[C]"]: ?
[string "=[C]"]: in function `UnitFactionGroup'
[string "@Interface/AddOns/Blizzard_InspectUI/InspectPVPFrame.lua"]:71: in function `InspectPVPFrame_Update'
[string "@Interface/AddOns/Blizzard_InspectUI/InspectPVPFrame.lua"]:60: in function <...erface/AddOns/Blizzard_InspectUI/InspectPVPFrame.lua:58>

Locals: (*temporary) = <function> defined =[C]:-1`

**Comment by iam3yal** [comment]
@Thekinghim The error is issued when invalid values are passed as arguments to functions (in this case `UnitFactionGroup` when called from `InspectPVPFrame.lua` in line 71) but the stack trace doesn't tell much.

**Comment by derfloh205** [comment]
@Thekinghim Thats an awful title for a github issue
if you have a question about something just ask it in the discord
the issues are there for well defined tasks and not for small talk
