### ISSUE TITLE
Match History: Character Dropdown duplicates Entries

### ISSUE THREAD

**Issue by Thekinghim** [PvPAssistant/PvPAssistant#111]
It does not work and its bugged 
![Skärmbild (281)](https://github.com/PvPAssistant/PvPAssistant/assets/151988881/d64458b4-5b74-4568-bf20-5625e60ad6b0)

**Comment by derfloh205** [comment]
maybe the bug with the server name again? what servers are those characters on?

**Comment by derfloh205** [comment]
Should be fixed by the newest GGUI Version (Pull) 2.1.17
