### ISSUE TITLE
character data shows up blank on clean instal

### ISSUE THREAD

**Issue by gerador20** [PvPAssistant/PvPAssistant#132]
Expected Results: character data should appear in the main addon hub with match history 

Actual Results: character data, match history shows up blank
![Screenshot 2024-04-15 220105](https://github.com/PvPAssistant/PvPAssistant/assets/167105091/755c50b5-021b-4c6a-99ad-3f0f6a128f70)

steps 
1.delete the addon and do a clean install (after the call with wille i suspect it might be something to do with a absolute clean install) 
make sure all traces of addon are deleted first 
2.install latest version on curse client 
3.enter a arena to collect some data 
4.check pvp assist main hub info

**Comment by derfloh205** [comment]
This is a follow up error of this issue: #31 which prevents data collection
