### ISSUE TITLE
addon conflict with method raid tools

### ISSUE THREAD

**Issue by gerador20** [PvPAssistant/PvPAssistant#135]
Expected Results: load both addons with no errors 

Actual results: the error shown only shows when both addons are enabled 
Message: ...erface/AddOns/Blizzard_InspectUI/InspectPVPFrame.lua:71: Usage: local factionGroupTag, localized = UnitFactionGroup(unitName [, checkDisplayRace])
Time: Tue Apr 16 10:28:12 2024
Count: 1
Stack: ...erface/AddOns/Blizzard_InspectUI/InspectPVPFrame.lua:71: Usage: local factionGroupTag, localized = UnitFactionGroup(unitName [, checkDisplayRace])
[string "=[C]"]: in function `UnitFactionGroup'
[string "@Interface/AddOns/Blizzard_InspectUI/InspectPVPFrame.lua"]:71: in function `InspectPVPFrame_Update'
[string "@Interface/AddOns/Blizzard_InspectUI/InspectPVPFrame.lua"]:60: in function <...erface/AddOns/Blizzard_InspectUI/InspectPVPFrame.lua:58>

Locals: (*temporary) = nil

addon versoin 2.0

steps 
1.install and enable method raid tools and pvp assistant

**Comment by derfloh205** [comment]
Now that we take data from an external source we dont need this dependency anymore which I guess will fix this problem
