### ISSUE TITLE
Player Recommendation: Save does not close frame

### ISSUE THREAD

**Issue by Thekinghim** [PvPAssistant/PvPAssistant#148]
Okey so it works but there is a slight problem like it doest close the frame it just gives a msg in the chat that you have made a comment

Steps.
Type a comment
Select a rank i give them
trying to send but the frame does not close it just sends a msg in the chat.

**Comment by derfloh205** [comment]
@Thekinghim Just thinking, maybe this is on purpose?
Since otherwise you could not change to a different person to also make a comment and save it

**Comment by Thekinghim** [comment]
I will play one more shuffle and send a video of me using the module!
