### ISSUE TITLE
Arena Quick Join: The Hidden Feature

### ISSUE THREAD

**Issue by iam3yal** [PvPAssistant/PvPAssistant#161]
Now that **Arena Quick Join** is not enabled by default it makes it a hidden feature! it's not even mentioned on the main page or anywhere.

**I expect it to be mentioned and credited as previously discussed with @Thekinghim .**

**Comment by Thekinghim** [comment]
I have not edited the description of anything. Have been fairly busy with real life but will sort it out

**Comment by iam3yal** [comment]
@Thekinghim No worries. Take your time, just making an issue about it so it's noticed.
