### ISSUE TITLE
Some text is overlapping in the arena quick guide

### ISSUE THREAD

**Issue by Thekinghim** [PvPAssistant/PvPAssistant#60]
![0e67e181022ea1edf3ee6e6daeb01c4d](https://github.com/derfloh205/PvPAssistant/assets/151988881/70e757a8-e1ef-482d-8d82-8c2a46115a66)

**Comment by derfloh205** [comment]
@Thekinghim do you want to do that?

Either make the icons smaller and move them a bit to the left
or
make the whole window bigger in width (including the column for the spell icons and names) so it fits

**Comment by Thekinghim** [comment]
Yea I can take a look at it, Problem is that it takes over 40min to get a que on solo shuffle. Is there any way I can test and modify it without being in a game?

**Comment by iam3yal** [comment]
@Thekinghim Yes, it's probably a good idea to create fakes for the APIs to test things more reliably and predictably, I can tell you guys how to do it correctly without hassles and I actually have a live example for it. :)

**Comment by Thekinghim** [comment]
Oh i see

**Comment by derfloh205** [comment]
nice, I got some debug flags currently for this too to fake a team with specific specs
just need to make it a bit more accessible for non devs ^^

**Comment by iam3yal** [comment]
@derfloh205 Imo it shouldn't be baked into the source at all and be external to the addon and completely removed on release through `.pkgmeta`, you can still have flags but if the file wouldn't exist then the flags wouldn't exist and you wouldn't have to do anything to do hide it, it would be completely and naturally removed from the source on release that's what I meant with no hassles or hassle free with my comment above.

**Comment by derfloh205** [comment]
> @derfloh205 Imo the fake data shouldn't be baked into the source at all and be external to the addon and completely removed on release through `.pkgmeta`, you can still have flags but if the file wouldn't exist then the flags wouldn't exist and you wouldn't have to do anything to do hide it, it would be completely and naturally removed from the source on release that's what I meant with no hassles or hassle free with my comment above.

Hm we can think more about that in discord maybe
Imo its not that bad to do that and sometimes even very beneficial

In my CraftSim Addon e.g. I ship a whole debug module with the whole addon
And I had very often the case that people used that to point out some bugs which otherwise would be hard to find without as a non dev :)

In a corporate environment I would absolutely agree with you!

**Comment by iam3yal** [comment]
@derfloh205 Sure we can continue on Discord.

Just a note, I don't have an issue shipping debugging flags even in corporate environment depends on whether it's useful to both developers and consumers. :)
