### ISSUE TITLE
Arena Guide: Possibility to open the guide manually

### ISSUE THREAD

**Issue by Thekinghim** [PvPAssistant/PvPAssistant#64]
Having access to a 'guide' that provides information about character spells and other details when entering an arena, but I prefer it not to automatically appear each time. Instead, I'd like to give users the option to open the 'guide' whenever they choose to do so.

This was provided by a few of our addon users

**Comment by derfloh205** [comment]
But where and how should it look like

**Comment by Thekinghim** [comment]
Use your imagination:P

**Comment by derfloh205** [comment]
Ill implement it as a simple slash command
