### ISSUE TITLE
Add offensive and defensive spells/ abilities

### ISSUE THREAD

**Issue by Thekinghim** [PvPAssistant/PvPAssistant#73]
Add the data I have collected with all the offensive and defensive abilities and put them into the ability catalog. Also make the icons that is for defensive, offensive and crowd control easier to understand, So just remove the 3 icons and put text. Also I want it to be in the center not to the left and maybe even integrate both of the new buttons into the class icons frame

**Comment by derfloh205** [comment]
@Thekinghim Where can I find the new data? Can you link a google sheet / the file ?

**Comment by Thekinghim** [comment]
It's under data. I made one completely new and then I just continued under your structure

**Comment by Thekinghim** [comment]
It's under data. I made one completely new and then I just continued under your structure

**Comment by derfloh205** [comment]
It seems after the ability list table ends the offensive and defensive ability are listed per class afterwards again
so the class tables are duplicated and as globals outside of the actual list

like

```
abilityList = {
  class1 = {ability1, ability2, ...},
  class2 = {ability1, ability2, ...},
  ...
}

class1 = {ability1, ability2, ...}
class2 = {ability1, ability2, ...}
```

So i guess if I change the structure it should appear
