### ISSUE TITLE
Deploy: Fix the deploy error to make github create releases

### ISSUE THREAD

**Issue by derfloh205** [PvPAssistant/PvPAssistant#80]
When I modified the BigWigs Packager to also pull and include submodules I think I broke the release packaging after the deploy process

I am no expert in this case and can only trial/error on this.

I assume @iam3yal is more into this than me so I suggest that he takes a look at it

Its not an urgent thing since the packaging and deploy itself does work but its wierd that the github action always fails and does not create releases

**Comment by iam3yal** [comment]
I'll look into it.

**Comment by iam3yal** [comment]
@derfloh205 I guess we can close this? 😉
