### ISSUE TITLE
ArenaQuickJoin: Add an Option / OptionsTab to show/hide button

### ISSUE THREAD

**Issue by derfloh205** [PvPAssistant/PvPAssistant#96]
I want PvPAssistant to have an option to show or hide the ArenaQuickJoin Button

**Scope**
- Add an options tab for the Join Button in the PvPAssistant Options module
- Add a checkbox that enables or disables the button

**Comment by Thekinghim** [comment]
Here @iam3yal

**Comment by iam3yal** [comment]
@Thekinghim I'm not messing with the options. @derfloh205 need to add it and it should be extremely easy to do.

**Comment by iam3yal** [comment]
@derfloh205 I'll add proper support for it so the module wouldn't load when it's hidden, I'll add myself to the issue.
