### ISSUE TITLE
Match History: Redesign Tooltip

### ISSUE THREAD

**Issue by Thekinghim** [PvPAssistant/PvPAssistant#99]
I was browsing and looking at reflex Hoover effect and I like that one a lot more then ours. I will include a picture of it and we can iterate on it and make it cleaner ![image](https://github.com/PvPAssistant/PvPAssistant/assets/151988881/f5f48dbf-b334-4fc8-aef4-f0cf4ff1e341)

**Comment by derfloh205** [comment]
![Image](https://github.com/PvPAssistant/PvPAssistant/assets/9341090/7063a3b3-ae0b-4bba-a453-54d9982be789)
